modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="kiwi"
version="${file.jarVersion}"
displayName="Kiwi"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kiwi"
description=""
license="MIT"

[[dependencies.kiwi]]
   modId="forge"
   mandatory=true
   versionRange="[31.1.18,)"
   ordering="NONE"
   side="BOTH"
