modLoader="javafml"
loaderVersion="[33,)"
license="MIT"

[[mods]]
modId="kiwi"
version="${file.jarVersion}"
displayName="Kiwi"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kiwi"
description=""

[[dependencies.kiwi]]
   modId="forge"
   mandatory=true
   versionRange="[33,)"
   ordering="NONE"
   side="BOTH"
