modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
modId="kiwi"
version="${file.jarVersion}"
displayName="Kiwi"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kiwi"
description=""

[modproperties.kiwi]
    catalogueItemIcon="minecraft:bookshelf" #Support for Catalogue mod
