modLoader="javafml"
loaderVersion="[26,)"
[[mods]]
modId="kiwi"
version="${file.jarVersion}" #mandatory
displayName="Kiwi"
credits="Thanks for this example mod goes to Java"
authors="Snownee, 3TUSK"
description='''
'''
