modLoader="javafml"
loaderVersion="[45,)"
license="MIT"

[[mods]]
modId="kiwi"
version="${file.jarVersion}"
displayName="Kiwi"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kiwi"
description="Minecraft modding library"
logoFile = "assets/kiwi/logo.png"

[[dependencies.kiwi]]
    modId="forge"
    mandatory=true
    versionRange="[45, )"
    ordering="NONE"
    side="BOTH"

[modproperties.kiwi]
    catalogueItemIcon="minecraft:bookshelf" #Support for Catalogue mod
