modLoader="javafml"
loaderVersion="[30,)"
[[mods]]
modId="kiwi"
version="${file.jarVersion}"
displayName="Kiwi"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kiwi"
description='''Huge thanks to my supporters:

粉鱼 Lioness131 皮蛋 路人玖 Cherls idyllic_bean 鱼加盐有点咸 洋葱菜菜子 面条公爵 车轮饼 mc00zhu 洛华 纪华裕 可爱至吉 ycccz 东篱下i Ruriri Meowsquito HAL9000 冰
'''

[[dependencies.kiwi]]
   modId="forge"
   mandatory=true
   versionRange="[28.1,)"
   ordering="NONE"
   side="BOTH"
