modLoader="javafml"
loaderVersion="[42,)"
license="MIT"

[[mods]]
modId="kiwi"
version="${file.jarVersion}"
displayName="Kiwi"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kiwi"
description="Minecraft modding library"

[[dependencies.kiwi]]
    modId="forge"
    mandatory=true
    versionRange="[42, )"
    ordering="NONE"
    side="BOTH"

[modproperties.kiwi]
    catalogueItemIcon="minecraft:bookshelf" #Support for Catalogue mod
